### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by HuakunShen** [andrewdavidmackenzie/libproc-rs#139]
https://mackenzie-serres.net/libproc-rs/libproc/index.html os down

**Comment by andrewdavidmackenzie** [comment]
Do Instill link to that (I will check)?
I was deferring to doc.rs now...

**Comment by andrewdavidmackenzie** [comment]
I see: I updated readme but left it in Cargo.toml by accident so it’s still appearing in crates.io

Thanks for the report, I will make JUST that change and republish, without cutting a new release just yet.
