### ISSUE TITLE
Macos-11 builds failing

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/libproc-rs#143]
The nightly cI runs seem to often fail on macos-11 builds recently. 

I don't think GH has removed to hem as they sometimes work, but they are definitely "struggling".

Maybe we can/should drop support for that version of macos?

Thoughts anyone?

**Comment by Skgland** [comment]
macos-11 was scheduled for removal last quarter, see https://github.com/actions/runner-images/issues/9255

**Comment by andrewdavidmackenzie** [comment]
Looks like it from

https://github.com/andrewdavidmackenzie/libproc-rs/actions/runs/9716309941

And macos-12 won't be far behind.

So, I'll remove macos-11 from the matrix, and we'll have to rely on similarity with macos-12 and user bug reports (or lack thereof) to keep it working for folks.
