### ISSUE TITLE
split proc_pid.rs into various files by area of functionality

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/libproc-rs#20]

**Comment by dalance** [comment]
@andrewdavidmackenzie  If splitting files takes a long time, could you merge https://github.com/andrewdavidmackenzie/libproc-rs/pull/19 and release before it?

**Comment by andrewdavidmackenzie** [comment]
I'm pretty busy at work and other projects right now. I can try and take a
look at the weekend.

If you submit the PR splitting stuff out before I get to it, I would merge
that.

Andrew

**Comment by andrewdavidmackenzie** [comment]
merged a split version of your PR.

Take a look and make sure it works as expected.

0.5.0 uploaded to crates. I'll do a tag on GH now (forgot!)

**Comment by dalance** [comment]
Thanks! I will try it.
