### ISSUE TITLE
Add Linux Equivalent: pidpath()

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [andrewdavidmackenzie/libproc-rs#33]
Get the path to the file being executed as the pid

**Comment by xd009642** [comment]
I'll tackle this one if you haven't started :+1:

**Comment by andrewdavidmackenzie** [comment]
OK, I read up on /proc FS and it looks like you should be able to get this from /proc/{pid}/exe which is a link to the executable file. Will need to figure out what the path the link points to is.

**Comment by xd009642** [comment]
Yeah so I've already pushed a PR for it #38 :+1:

**Comment by andrewdavidmackenzie** [comment]
Merged. We can see how we can make a reliable (cross-platform) test that checks it works (as opposed to the current one that checks pid = -1 doesn't work) in separate work.

Thanks for the contribution

**Comment by andrewdavidmackenzie** [comment]
Fixed by https://github.com/andrewdavidmackenzie/libproc-rs/pull/38
