### ISSUE TITLE
Publish crate version 0.1.1?

### ISSUE THREAD

**Issue by jvns** [andrewdavidmackenzie/libproc-rs#6]
I want to publish a crate that depends on libproc, but I can't because the current published version has the double-free bug fixed in this commit. https://github.com/andrewdavidmackenzie/libproc-rs/commit/e7d2319eb6369e7cd5c7c983caa643441206f104

**Comment by andrewdavidmackenzie** [comment]
Hi Julia, I can publish an update - no worries.

I started it originally inspired to do something like ruby spy for ruby live debugging, so happy to hear you use it - although I got distracted (and discouraged by all the many Apple Mac OS X variants of their code...) and never really finished it.....

Maybe time to do some more work on it and get others to do the Linux version...

**Comment by jvns** [comment]
thank you! i also find all the OS X complexity pretty discouraging, so it was a huge help to find crates which have taken on trying to tame it a little bit :)

if you make ruby debugging tools i'd love to see them!

**Comment by andrewdavidmackenzie** [comment]
I think you made the one I was thinking about! :-)

**Comment by andrewdavidmackenzie** [comment]
Try this: https://crates.io/crates/libproc   a 0.2.0 release.

A bit of a rush (late here in Spain :-) ) so let me know if any issues or enhancement requests....

Seems I have some code warnings in there I haven't cleaned - and it looks like I have local changes I was working on and never finished (this was published from a clean download of the 0.2.0 GH release though).

**Comment by andrewdavidmackenzie** [comment]
@jvns  You might want to modify the blog post (https://jvns.ca/blog/2018/01/26/mac-memory-maps/) to point people to the new release with the fix.

BTW: If you think it's useful to add new methods into libproc-rs for your needs, feed free to submit issues and I'll see what I can do.
