### ISSUE TITLE
How to collect memory information for a process on non-Mac OS?

### ISSUE THREAD

**Issue by renatoathaydes** [andrewdavidmackenzie/libproc-rs#61]
Hey!

This library is great, but unfortunately I ran into an issue where to collect process memory, apparently I need to use `libproc::pid_rusage`? But that seems to be only available on Mac OS?

The docs say this "was added in Mac OS X 10.9" but it wasn't clear to me it was not available on other OSs.

What I want is probably just "resident memory" (in lay terms, how much RAM the process is using). Is there a way to get that which works on all Windows, Linux and Mac OS?

Thanks.

**Comment by andrewdavidmackenzie** [comment]
There maybe a way to get it on Linux (adding a Linux implementation for that method), such as parsing /procfs or similar...I'd have to look into that.

On Window I have no idea, and I haven't done any windows support and don't have a windows machine to do so (or any knowledge) I'm afraid.

**Comment by andrewdavidmackenzie** [comment]
Maybe this is the easy way to do it, similar to some of the other methods I already have on linux, reading procfs:

https://unix.stackexchange.com/questions/224015/memory-usage-of-a-given-process-using-linux-proc-filesystem

**Comment by andrewdavidmackenzie** [comment]
So, I have added GitHub action to re-establish CI (migration to travis-ci.com a disaster) and could do this issue, if you could share what you think is the best implementation regarding some of those ambiguities about RAM usage that are mentioned in that article.
(https://unix.stackexchange.com/questions/224015/memory-usage-of-a-given-process-using-linux-proc-filesystem)

**Comment by renatoathaydes** [comment]
@andrewdavidmackenzie will have a look. I noticed that [procs](https://crates.io/crates/procs) uses your crate and it seems to support memory on Linux (from a brief look at it). I couldn't manage to find how they do it, but you might understand their code better, maybe have a look?

**Comment by renatoathaydes** [comment]
Ah, just needed to look a bit more :) they seem to use [procfs](https://crates.io/crates/procfs) on Linux, and your crate on MacOS!

I will do the same :) maybe this will help you make this crate a bit more OS-agnostic!

**Comment by andrewdavidmackenzie** [comment]
If you share what they do, I can wrap the parsing of procfs in that method,
as I already do for other things

**Comment by renatoathaydes** [comment]
It seems they collect all information about the process here:

https://github.com/eminence/procfs/blob/master/src/process/stat.rs#L244

Virtual memory size is here:

https://github.com/eminence/procfs/blob/master/src/process/stat.rs#L283

Basic text parsing :D easy to use this for Linux.

**Comment by andrewdavidmackenzie** [comment]
Will look at doing this, reading VRAM at least as a starter 
who is "they" that use this crate and procfs BTW?

**Comment by renatoathaydes** [comment]
> I noticed that procs uses your crate...

> they seem to use procfs on Linux, and your crate on MacOS!

**Comment by andrewdavidmackenzie** [comment]
OK, I will parse:

"/proc/[pid]/status"

and use the "VmSize" line
