### ISSUE TITLE
MacOS: accept a typeinfo argument for listpids

### ISSUE THREAD

**Issue by mjpieters** [andrewdavidmackenzie/libproc-rs#85]
Currently, `listpids` sets the `typeinfo` argument to `proc_listpids` to `0`:

https://github.com/andrewdavidmackenzie/libproc-rs/blob/a8e050107c9cfe27fa7504874e6a193fdc2d685a/src/libproc/proc_pid.rs#L161-L162

That makes perfect sense for `ProcType::ProcAllPIDS`, but when using any of the other `ProcType` variants, a call to `proc_listpids` only makes sense **if you pass in the matching ID as the `typeeinfo` value**, e.g. for `ProcType::ProcPGRPOnly`, you can pass in the program group id (PGID) and get only those processes that are part of the process group.

To illustrate, you could try creating a process with the [`command_group` crate](https://docs.rs/command-group), such as a shell script that spawns a couple of `sleep <large number>` background processes. This gets you a `GroupChild` struct with a `.id()` method returning the process group ID. If you then use `proc_listpids(proc_pid::ProcType::ProcPGRPOnly, child.id(), buffer_ptr, buffer_size)` the buffer is filled with the PIDs of the processes in that process group.

The (abandoned?) darwin-libproc crate [has separate functions for each `ProcType` variant](https://github.com/heim-rs/darwin-libproc/blob/master/darwin-libproc/src/list_pids.rs#L36-L64) to pass in the corresponding identifiers.

Can libproc-rs please offer the same options?

**Comment by mjpieters** [comment]
I'm perfectly willing to make a PR for this, by the way, but would like to know how to structure the code for this. Would utility functions like darwin-libproc has be preferable? Or should the ProcType enum be replaced with one where all variants except  `ProcAllPIDS` become structs with a single field? E.g.

```rust
pub enum ProcType {
    /// All processes
    ProcAllPIDS,
    /// Only PGRP Processes
    ProcPGRPOnly { pid: u32 },
    /// Only TTY Processes
    ProcTTYOnly { tty: u32 },
    /// Only UID Processes
    ProcUIDOnly { uid: u32 },
    /// Only RUID Processes
    ProcRUIDOnly { ruid: u32 },
    /// Only PPID Processes
    ProcPPIDOnly { ppid: u32 },
}
```

and then use a separate, private enum to handle the mapping to u32  value?

That way you could then use:

```rust
let pg_procs = proc_pid::listpids(proc_pid::ProcType::ProcPGRPOnly { some_group_child.id() });
```

and not have to worry about callers having to remember to pass in `0` for the `typeeinfo` parameter  when asking for all pids with the `proc_pid::ProcType::ProcAllPIDs` proc type.

**Comment by mjpieters** [comment]
Some more context: take a look at the [Darwin syscall library interface `libproc.c` file](https://github.com/apple/darwin-xnu/blob/8f02f2a044b9bb1ad951987ef5bab20ec9486310/libsyscall/wrappers/libproc/libproc.c), which is the interface that libproc-rs is wrapping.

Note that `darwin-libproc` gives you the same utility functions as listed in that file; e.g. `proc_listallpids(...)` which calls `proc_listpids(PROC_ALL_PIDS, (uint32_t)0, ...)` and `proc_listpgrppids(pid_t pgrpid, ...)` which calls `proc_listpids(PROC_PGRP_ONLY, (uint32_t)pgrpid, ...)`, etc.

This makes me think that it'd be better to echo that structure here.

**Comment by andrewdavidmackenzie** [comment]
Feel free to prepare a PR (if you want) while I catch-up on your analysis. Will take me a day or two.

Especially interested to understand any not-backwards-compatibility introduced by the change, plus having any tests related to that.

**Comment by mjpieters** [comment]
I've created a draft PR #86 to give you an idea of what the new API would look like. The Linux version of `listpids` is still no more than a sketch, in that it only contains notes on how to implement each filter right now. If this is something you'd like to see merged, in principle, I'll flesh those parts out.

**Comment by andrewdavidmackenzie** [comment]
I just did a (quickish) review and didn't see anything jump out at me, so I think it would be good to complete it yes.

Quick comments:
- want to bump the version number in the same PR?
- being 0.x.y there's no (AFAIK) _proper_ way to signal deprecation of methods. But we could move to 0.20.0 maybe to signal significant change.
- If I had known better (more rust) when I wrote the first version, the module and bin/lib structure would have been better and the API better (without the extra "level" introduced by being binary and lib crate). To do so I would move my "example" binaries, to be real cargo examples.... just mentioning in case you wanted to add an example that uses the new processes API exposed. Plus thoughts I have had to "fixing that once and for all", changing the API and making a breaking version. FYI.
- There's plenty of scope for cleanup, improvement and restructureing macos/linux code....if you were interested in helping....but probably best to keep to separate PRs.

**Comment by mjpieters** [comment]
> * want to bump the version number in the same PR?

Sure!

> * being 0.x.y there's no (AFAIK) _proper_ way to signal deprecation of methods. But we could move to 0.20.0 maybe to signal significant change.

Yes, that's what I'd suggest.

> * If I had known better (more rust) when I wrote the first version, the module and bin/lib structure would have been better and the API better (without the extra "level" introduced by being binary and lib crate). To do so I would move my "example" binaries, to be real cargo examples.... just mentioning in case you wanted to add an example that uses the new processes API exposed. Plus thoughts I have had to "fixing that once and for all", changing the API and making a breaking version. FYI.

I updated the existing example code.

I'd start with figuring out a new API layout and just.. make that happen. Better to refactor earlier than later, Rust's built-in support for deprecation will help downstream users move along if and when they are ready.

> * There's plenty of scope for cleanup, improvement and restructureing macos/linux code....if you were interested in helping....but probably best to keep to separate PRs.

I'm not sure I have the time or energy to go full clean-up here, at the moment. :-/

**Comment by andrewdavidmackenzie** [comment]
OK, understood. We've all got lots going on!! :-)

**Comment by mjpieters** [comment]
@andrewdavidmackenzie the PR is starting to come together, finally. Sorry for the slow pace there!

Could you approve workflow runs on the PR? There is only so much I can do on my Mac and in Docker, I'd need to see how the test suite runs on GitHub runners to make sure I am not missing something tricky.

**Comment by andrewdavidmackenzie** [comment]
Workflow run approved!

**Comment by andrewdavidmackenzie** [comment]
Thanks for the effort BTW, I know how hard it is to allocate time to these things... I'll try to keep up with you though! :-)
